# Generated by Django 5.2.6 on 2026-02-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('dewormed', models.BooleanField(default=False)),
                ('neutered_spayed', models.BooleanField(default=False)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('microchip_id', models.CharField(blank=True, max_length=100)),
                ('vet_name', models.CharField(blank=True, max_length=100)),
                ('vet_contact', models.CharField(blank=True, max_length=20)),
                ('diet_type', models.CharField(blank=True, max_length=100)),
                ('activity_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('temperament', models.CharField(blank=True, max_length=100)),
                ('adoption_ready', models.BooleanField(default=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='myapp.pet')),
            ],
        ),
    ]
