# Generated by Django 5.2.6 on 2026-02-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctorappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='preferred_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='preferred_time',
            new_name='appointment_time',
        ),
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='pet_species',
            new_name='pet_type',
        ),
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='problem_description',
            new_name='symptoms',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
