# Generated by Django 5.2.6 on 2026-02-17 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_preferred_date_doctorappointment_appointment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCareBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_species', models.CharField(max_length=50)),
                ('pet_age', models.PositiveIntegerField()),
                ('pet_gender', models.CharField(blank=True, max_length=20)),
                ('health_notes', models.TextField(blank=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('special_diet', models.BooleanField(default=False)),
                ('injection_required', models.BooleanField(default=False)),
                ('vaccine_required', models.BooleanField(default=False)),
                ('extra_care', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_care_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
