# Generated by Django 5.2.6 on 2026-02-18 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_petcarebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('package_type', models.CharField(choices=[('BASIC_BATH', 'Basic Bath'), ('HAIRCUT', 'Hair Cut & Styling'), ('NAIL_CLIP', 'Nail Clipping'), ('EAR_CLEAN', 'Ear Cleaning'), ('TICK_TREATMENT', 'Tick Treatment'), ('FULL_GROOM', 'Full Grooming Package')], max_length=20)),
                ('visit_type', models.CharField(choices=[('CENTER', 'Center Visit'), ('HOME', 'Home Visit')], max_length=10)),
                ('preferred_groomer', models.CharField(blank=True, max_length=100)),
                ('appointment_datetime', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
