# Generated by Django 5.2.6 on 2026-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_groomingbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('TOY', 'Toys'), ('BED', 'Beds'), ('LEASH', 'Leashes'), ('CLOTHING', 'Clothing'), ('COLLAR', 'Collars'), ('SUPPLEMENT', 'Supplements')], max_length=20)),
                ('pet_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
