# Generated by Django 5.2.6 on 2026-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_aicachedreport_pendingregistration_accessory_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
