# Generated by Django 5.2.6 on 2026-07-11 07:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_passwordreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='rating',
        ),
        migrations.AddField(
            model_name='accessory',
            name='bought_past_month_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_prime_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Maximum Retail Price'),
        ),
        migrations.AddField(
            model_name='food',
            name='bought_past_month_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='is_prime_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Maximum Retail Price'),
        ),
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='bought_past_month_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Estimated units bought last month'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_prime_eligible',
            field=models.BooleanField(default=True, verbose_name='Eligible for Prime Fast Delivery'),
        ),
        migrations.AddField(
            model_name='pet',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Maximum Retail Price'),
        ),
        migrations.AddField(
            model_name='pet',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.food'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_petportal_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
