# Generated by Django 5.2.6 on 2026-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor_appointment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grooming',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pet_care',
        ),
        migrations.AddField(
            model_name='review',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
