# Generated by Django 5.2.6 on 2026-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_doctorappointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Settings', max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed tax fee in INR', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee in INR', max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='GST Percentage', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform fee in INR', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
