# Generated by Django 5.2.6 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_checkoutsetting_order_delivery_fee_order_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='accessories/videos/'),
        ),
        migrations.AddField(
            model_name='food',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
        migrations.AddField(
            model_name='food',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='foods/videos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pets/videos/'),
        ),
    ]
