# Generated by Django 5.2.6 on 2026-07-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_accessory_image2_accessory_video_food_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reviews/videos/'),
        ),
    ]
